# Generated by Django 3.1.1 on 2020-09-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=6)),
                ('userName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeInOut', models.DateTimeField()),
                ('typeInOut', models.CharField(max_length=2)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attlab.users')),
            ],
        ),
    ]
